Create anonymous report form. First attempt at it.
LondonCSS/website pull request #9
Opened 2019-05-08 16:04 UTC by ohhelloana

I think this will work. Fingers crossed.

2019-05-08 17:36 UTC, oliverturner requested changes
This is great! 

One small ask: since this project uses Yarn, would you mind deleting  `package-lock.json`? 

As soon as that's gone I'll be delighted to approve :)

2019-05-08 17:36 UTC, oliverturner commented on src/_includes/partials/anonymous-contact-form.njk
> +    <p>
Probably worth adding the bot-trapping [honeypot input](https://www.netlify.com/docs/form-handling/#spam-filtering) too

2019-05-08 17:36 UTC, oliverturner commented on src/about-us.njk
> +  London CSS has been curated by [Ana Rodrigues](https://twitter.com/ohhelloana) and [Oliver Turner](https://twitter.com/oliverturner) since late 2018.
Sorry about that!

2019-05-08 17:44 UTC, ohhelloana commented on src/about-us.njk
> +  London CSS has been curated by [Ana Rodrigues](https://twitter.com/ohhelloana) and [Oliver Turner](https://twitter.com/oliverturner) since late 2018.
no worries! i really don't mind :)

2019-05-08 17:52 UTC, oliverturner commented on src/_includes/partials/anonymous-contact-form.njk
> +    </p>
So we just need to add an input whose name matches the value of the `data-honeypot` attribute, a `.hidden` class to the CSS and we're good 👍

```html
<p class="hidden">
  <label>Don’t fill this out if you're human: 
    <input name="bot-field" />
  </label>
</p>
```

2019-05-09 13:39 UTC, oliverturner commented
Closing this as superseded by #10

2019-05-09 13:39 UTC, closed without merging